#!/usr/bin/env bash
# Sync qvpic sources into the self-contained Hugging Face Space folder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$ROOT/space/qvpic"

mkdir -p "$DST"
rm -rf "$DST/src"

COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo local)"
UPDATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$ROOT/web/build_info.py" <<EOF
"""Auto-generated by scripts/sync_hf_space.sh — do not edit by hand."""

BUILD_COMMIT = "$COMMIT"
BUILD_UPDATED_UTC = "$UPDATED"
EOF

rsync -a --delete \
  --exclude='__pycache__' \
  --exclude='*.pyc' \
  --exclude='*.egg-info' \
  "$ROOT/src/" "$DST/src/"
mkdir -p "$DST/configs"
cp "$ROOT/web/hf_default.yaml" "$DST/configs/default.yaml"
mkdir -p "$DST/facts"
cp "$ROOT/web/demo_public_facts.json" "$DST/facts/demo_public_facts.json"
cp "$ROOT/web/demo_core.py" "$DST/"
cp "$ROOT/web/build_info.py" "$DST/"
cp "$ROOT/web/gradio_demo.py" "$DST/app.py"

cat > "$DST/requirements.txt" <<'EOF'
--extra-index-url https://download.pytorch.org/whl/cpu
torch>=2.4.0,<3.0.0
numpy>=1.24.0,<3.0.0
scipy>=1.10.0
matplotlib>=3.7.0
pyyaml>=6.0
pydantic==2.10.6
sentence-transformers>=2.2.0
tqdm>=4.60.0
python-dotenv>=1.0.0
omegaconf>=2.3.0
scikit-learn>=1.3.0
huggingface-hub>=0.23.0
EOF

{
  cat <<'EOF'
---
title: QVPIC Identity Conduit
emoji: 🌀
colorFrom: purple
colorTo: blue
sdk: gradio
sdk_version: 5.12.0
python_version: 3.12
app_file: app.py
pinned: false
license: mit
short_description: Quaternion vortex persistent identity — browser demo
---

EOF
  cat "$ROOT/docs/HF_SPACE_README.md"
} > "$DST/README.md"

echo "Synced → $DST"
ls -la "$DST"